
name: Build and Test

on: [push]

jobs:
   test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and test
        run: |
          yarn install
          yarn jest
   build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and build
        run: |
          yarn install
          yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: update_dotenv_build_artifacts
          path: |
            dist/
            es/
            lib/